services:

  sharepass:
    restart: unless-stopped
    container_name: sharepass
    build: 
      context: .
      dockerfile: Dockerfile.sharepass
    ports:
      - "8081:8080"
    environment:
      - TZ=${DOCKER_TZ}
      - MAX_USES_QUOTA=10
      - MAX_ATTEMPTS=3
      - SECRET_EXPIRY_MINUTES=1440  # 24 hours
      - QUOTA_RENEWAL_MINUTES=60  # 1 hour
      - PURGE_INTERVAL_MINUTES=5
      - INTERNAL_IP=127.0.0.1
      - INTERNAL_PORT=8080
      - ANALYTICS_SCRIPT=
    #volumes:
    #  - /snapfile/database:/app/database
